server:
  port: 8071

spring:
  application:
    name: "config-server"
  profiles:
#    active: git
    active: native
  cloud:
    config:
      server:
        native:
          search-locations: classpath:/config/
#          search-locations: file:///${user.home}/config-repo/
#        git:
#          uri: "https://github.com/demo"
#          default-label: master



